name: Missing File Check

on:
  schedule:
    - cron: '0 0 * * *' # chạy mỗi ngày lúc 00:00 UTC
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'false = chỉ kiểm tra, true = kiểm tra và thêm file thiếu'
        default: 'false'
      workingOrgs:
        description: 'Tên organization cần kiểm tra'
        default: 'ttan-org'
  push:
    branches: [ "master" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Set default values for dryRun and workingOrgs
        run: |
          echo "dryRun=${{ github.event.inputs.dryRun || 'true' }}" >> $GITHUB_ENV
          echo "workingOrgs=${{ github.event.inputs.workingOrgs || 'axonivy-market' }}" >> $GITHUB_ENV

      - name: Build with Maven
        working-directory: ./github-repo-manager
        run: mvn clean install

      - name: Run GitHub Missing Files
        working-directory: ./github-repo-manager
        run: |
          mvn -B clean compile exec:java \
            -DGITHUB.TOKEN="${{ secrets.TOKEN }}" \
            -DDRY_RUN="${{ env.dryRun }}" \
            -Dexec.mainClass="com.axonivy.github.file.GitHubMissingFiles" \
            -Dexec.args="${{ github.actor }}" \
            -DGITHUB.WORKING.ORGANIZATIONS="${{ env.workingOrgs }}"
